project_id = "ftuxnhmjhjbuzxbvjygm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 54328

[auth.external]
enabled = false

[edge_functions]
enabled = true

[functions.research-controller]
verify_jwt = true

[functions.sentiment-agent]
verify_jwt = true

[functions.competitor-agent]
verify_jwt = true

[functions.trend-agent]
verify_jwt = true

[functions.insight-agent]
verify_jwt = true

[functions.generate-pdf-report]
verify_jwt = true