// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftuxnhmjhjbuzxbvjygm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0dXhuaG1qaGpidXp4YnZqeWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjQ3MjksImV4cCI6MjA3MDc0MDcyOX0.3E7uGvZYwez5mT4nLKvh_GbYIo9aPI4z-8BTzumxEog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});